### PR TITLE
remove Engage button from spot, margin trade.

### PR DESCRIPTION
**Pull request by rick23p**

### CODE REVIEW

**Comment by rick23p** [comment]
@t-z-u please check if it's working as you want

**Comment by rick23p** [comment]
closes #1152

**Review by creed-victor — APPROVED** [review]
Approving, but in my opinion having "Engage Wallet" or any other indicator which informs user why buttons are disabled was much better approach

**Comment by rick23p** [comment]
@creed-victor I agree with you. It's easier for users to know what's going on and engage easily.
@t-z-u What do you think?

**Review by pietro-maximoff — APPROVED** [review]

**Pull request merged**
