### PR TITLE
Add translation strings for #143

### PR DESCRIPTION
**Pull request by soulBit**
Added strings for all text that is referenced in #143, with the exception of this one (as I believe this is just a temporary warning):
https://github.com/DistributedCollective/Sovryn-frontend/issues/143#issuecomment-766356682

All of these will need appropriate translations, I have just copied over the english text.

There is one string that I spotted in NotificationFormContainer::86 that looks like it needs translation, but I'm not sure how you would like to handle this one as there are some newline characters and piping that probably shouldn't go into the translation json:
 `${timestamp} \n \n Please confirm that the details associated with this account will now be: \n \n Username: ${name} \n Email: ${email}`

I also reviewed the rest of the Components/Containers in the app and have found a number of other locations where translations should be applied - let me know if you'd like a list of those submitted as separate ticket/pull request.

### CODE REVIEW

**Comment by creed-victor** [comment]
Hey, thanks.
Yes thats temporary so it's no need to translate. 

`${timestamp} \n \n Please confirm that the details associated with this account will now be: \n \n Username: ${name} \n Email: ${email}` is a message that is being send to user's crypto wallet for signing so it shouldn't be translatable too.

As for missing translations in other components and containers - yes, we want all of them translated but we have new design which will come within a couple of weeks so maybe it's best to skip it - most likely great chunk of texts will be changed there.

**Comment by bitcoinuser** [comment]
> new design which will come within a couple of weeks so maybe it's best to skip it

Where do I see this new design?

**Comment by soulBit** [comment]
Thanks @creed-victor!

**Comment by creed-victor** [comment]
> Where do I see this new design?

@bitcoinuser not sure if it's already there, but all designs should be here: https://drive.google.com/drive/folders/1e_VljWpANJe0o4VmIkKU5Ewo56l9iMaM?usp=sharing

**Comment by bitcoinuser** [comment]
Hi @soulBit, please add this Update button string too. Thanks

Captura de tela de 2021-01-31 15-52-25

**Pull request merged**
