### PR TITLE
feat(xusd): swap xusd amm pool contracts

### PR DESCRIPTION
**Pull request by creed-victor**
Testnet used wrong XUSD token contract address, this PR swaps it to the correct one.

There is now 2 XUSD tokens in the testnet, old one has sufix _legacy in the name.
Reason for this is that we can't remove it right away because some contract calls returns old xusd address and FE tries to link it to the asset, when not found - most of the components crashes.

AC:
- user can deposit to XUSD/RBTC AMM pool
- user can withdraw from XUSD/RBTC pool
- user can deposit to XUSD lending pool
- user can withdraw from XUSD lending pool
- user can take XUSD loan
- user can take loan using XUSD as collateral
- user can return XUSD loan
- user can make swaps using XUSD
- user can make swaps to XUSD
- user can open margin trade order using XUSD as collateral
- user can close trade order
- deposit to XUSD using bridge works
- withdraw from XUSD using bridge works

### CODE REVIEW

**Comment by tiltom** [comment]
I don't think I should see `XUSD_legacy` on Borrow page.

Screenshot 2022-05-27 at 9 08 29

**Comment by tiltom** [comment]
I see `XUSD_legacy` on Lending page as well.
Screenshot 2022-05-27 at 9 11 55

**Comment by tiltom** [comment]
When I want to swap, it uses `XUSD_legacy` again (balance is `0.38488` instead of `4121,...`).
Screenshot 2022-05-27 at 9 13 55

**Comment by tiltom** [comment]
Deposit in XUSD lending pool works fine but I am getting `execution reverted` on Withdraw: https://dashboard.tenderly.co/tx/rsk-testnet/0x0f0341fec13c8f7ce8e6c239fcafcc66a57c4707d64817b09acee8ea0439a62e ..

**Review by tiltom — CHANGES_REQUESTED** [review]
The PR looks good but there are failing contract calls that need to be investigated.

**Comment by creed-victor** [comment]
It's ready to review and test again, with small amounts. (Except for margin trading - price of xusd is out of sync and needs to be rebalanced first)

**Review by tiltom — APPROVED** [review]
I tested the same scenarios as before (+ Add to collateral and Repay loan) and everything works fine (except margin trading but it's not possible to test it at the moment).

**Review by soulBit — APPROVED** [review]

**Pull request merged**
