### PR TITLE
Remove leverage from SOV margin trade

### PR DESCRIPTION
**Pull request by tiltom**
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2231505190

### CODE REVIEW

**Review by soulBit — APPROVED** [review]
Refactored SOV leverage const name and added small explanatory comment - changes look good 👍🏻

**Review by creed-victor — DISMISSED** [review]

**Comment by creed-victor** [comment]
Changes ok, but we could improve it with trading pair dictionary and add available leverage as a config there instead (in case there will be more pairs with different leverage options in the future).

**Comment by tiltom** [comment]
> Changes ok, but we could improve it with trading pair dictionary and add available leverage as a config there instead (in case there will be more pairs with different leverage options in the future).

I thought this is a one-off thing that's why I made it this way but I can add it to trading pair dictionary so it's more universal.

**Review by creed-victor — APPROVED** [review]

**Comment by creed-victor** [comment]
> I thought this is a one-off thing that's why I made it this way but I can add it to trading pair dictionary so it's more universal.

Should be one-off thing, but I remember changing leverage min/max a year ago :D Thanks

**Review by JoeStorm99 — APPROVED** [review]
tested and all looks fine but need to complete testing on staging due to an intermittent error on "price disagreement".

**Review by soulBit — APPROVED** [review]

**Pull request merged**
