### PR TITLE
[Swap] - add data ids

### PR DESCRIPTION
**Pull request by pietro-maximoff**
https://sovryn.monday.com/boards/2218344956/pulses/2592952245?doc_id=2593014092&userId=26728963

### CODE REVIEW

**Review by creed-victor — APPROVED** [review]

**Review by ShynRou — DISMISSED** [review]

**Comment by tiltom** [comment]
I think that search inputs should be in this format to be consistent with the rest of the attributes - `swap-[receive/send]-search-input`.

image

**Comment by tiltom** [comment]
`swap-arbitrage-submit-button` maybe?

image

**Comment by pietro-maximoff** [comment]
>

**Comment by pietro-maximoff** [comment]
> I think that search inputs should be in this format to be consistent with the rest of the attributes - `swap-[receive/send]-search-input`. What do you think @soulBit ?
> 
> image

agree with that. @JoeStorm99 is it ok for you if i add Tiltom's suggestion

**Review by JoeStorm99 — DISMISSED** [review]

**Comment by soulBit** [comment]
@pietro-maximoff yep let's go with tiltom's suggestions here, I'll update the spec accordingly

**Review by soulBit — APPROVED** [review]

**Pull request merged**
