### PR TITLE
Fix/lending issues

### PR DESCRIPTION
**Pull request by rick23p**

### CODE REVIEW

**Comment by bitcoinuser** [comment]
I'm not a developer but I think Mint and Burn words should be on src/locales/en/translation.json, no? So I'll be able to translate to Portuguese Brazilian. Thanks

**Comment by bitcoinuser** [comment]
Other feedback: Why show asset RBTC names? In front already has the RBTC name.

Captura de tela de 2021-06-30 10-50-10

**Comment by bitcoinuser** [comment]
> Other feedback: Why show asset RBTC names? In front already has the RBTC name.
> 
> Captura de tela de 2021-06-30 10-50-10

There's a bug here too. If I change to English, I still see the names on popup as Portuguese Brazilian.

**Comment by bitcoinuser** [comment]
And a new suggestion: 

I think on popup should show some more infos like: The APY of last 30 days and the APY of last year. So people will have an idea of past APY.

**Comment by rick23p** [comment]
> I'm not a developer but I think Mint and Burn words should be on src/locales/en/translation.json, no? So I'll be able to translate to Portuguese Brazilian. Thanks

we are using deposit/withdraw from the translation for Mint/Burn. So you can translate those.

**Comment by bitcoinuser** [comment]
> > I'm not a developer but I think Mint and Burn words should be on src/locales/en/translation.json, no? So I'll be able to translate to Portuguese Brazilian. Thanks
> 
> we are using deposit/withdraw from the translation for Mint/Burn. So you can translate those.

Sorry, I didn't understand. Could you please point to me the strings on PT-R file that I can translate the Mint/Burn words? Thanks.

**Comment by bitcoinuser** [comment]
> > I'm not a developer but I think Mint and Burn words should be on src/locales/en/translation.json, no? So I'll be able to translate to Portuguese Brazilian. Thanks
> 
> we are using deposit/withdraw from the translation for Mint/Burn. So you can translate those.

Hi @rick23p, I think needs new strings to those words. On Portuguese Brazilian doesn't looks good the words deposit/withdraw. For example: The deposit/withdraw is translated for the buttons as Emprestar/Resgatar but on history should be Emprestado/Resgatado. So the new strings are necessary, thanks.

**Review by creed-victor — APPROVED** [review]

**Comment by bitcoinuser** [comment]
> > I'm not a developer but I think Mint and Burn words should be on src/locales/en/translation.json, no? So I'll be able to translate to Portuguese Brazilian. Thanks
> 
> we are using deposit/withdraw from the translation for Mint/Burn. So you can translate those.

Ok, I agree.

**Pull request merged**
