### PR TITLE
Use sass instead of node-sass

### PR DESCRIPTION
**Pull request by tiltom**

### CODE REVIEW

**Comment by tiltom** [comment]
@ShynRou - it went surprisingly smooth and without style changes so take a look at it if it's ok. I went through the whole app and everything looks as it should (I also went through all of the `.scss` files and there are no errors or anything).

**Comment by tiltom** [comment]
@JoeStorm99 - this will need thorough testing once @ShynRou and @creed-victor finish their review. You will need to go through the whole app if you don't find some broken styles (but only after their review).

**Comment by ShynRou** [comment]
@tiltom Build is not working anymore, you need to migrate some stuff, because of the different APIs of DartSass and LibSass.
Please also fix the deprecation warnings.
<details>
<summary>view build output</summary>

```
yarn run v1.22.10
$ node scripts/build.js
Creating an optimized production build...
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($pt-grid-size * 1.8, $pt-font-size)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
35 │ $pt-line-height: ($pt-grid-size * 1.8) / $pt-font-size + 0.0001 !default;
   │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@blueprintjs/core/src/common/_variables.scss 35:18  @import
    node_modules/@blueprintjs/core/src/blueprint.scss 9:9            @import
    src/styles/sass/styles.scss 7:9                                  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($pt-grid-size, 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
47 │ $pt-border-radius: floor($pt-grid-size / 3) !default;
   │                          ^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@blueprintjs/core/src/common/_variables.scss 47:26  @import
    node_modules/@blueprintjs/core/src/blueprint.scss 9:9            @import
    src/styles/sass/styles.scss 7:9                                  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($pt-grid-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
342 │     margin-right: $pt-grid-size / 2;
    │                   ^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@blueprintjs/core/src/_typography.scss 342:19  @import
    node_modules/@blueprintjs/core/src/blueprint.scss 13:9      @import
    src/styles/sass/styles.scss 7:9                             root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($pt-grid-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
411 │     margin-bottom: $pt-grid-size / 2;
    │                    ^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@blueprintjs/core/src/_typography.scss 411:20  @import
    node_modules/@blueprintjs/core/src/blueprint.scss 13:9      @import
    src/styles/sass/styles.scss 7:9                             root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($pt-grid-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
417 │     margin-top: $pt-grid-size / 2;
    │                 ^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@blueprintjs/core/src/_typography.scss 417:17  @import
    node_modules/@blueprintjs/core/src/blueprint.scss 13:9      @import
    src/styles/sass/styles.scss 7:9                             root stylesheet

Failed to compile.

./src/styles/sass/styles.scss
SassError: (path: (fill: #5c7080)) isn't a valid CSS value.
   ╷
39 │       background: svg-icon("16px/chevron-right.svg", (path: (fill: $pt-icon-color)));
   │                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@blueprintjs/core/src/components/breadcrumbs/_breadcrumbs.scss 39:54  @import
  node_modules/@blueprintjs/core/src/components/_index.scss 5:9                      @import
  node_modules/@blueprintjs/core/src/blueprint.scss 16:9                             @import
  src/styles/sass/styles.scss 7:9                                                    root stylesheet


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

**Comment by tiltom** [comment]
We decided not to continue on this, see the comment - https://github.com/DistributedCollective/Sovryn-frontend/issues/1492

**Pull request closed without merging**
