### PR TITLE
[Staking] - fix the issue with stake/unstake 100% of SOV

### PR DESCRIPTION
**Pull request by pietro-maximoff**
+ fix error in console with forfeit

### CODE REVIEW

**Comment by ShynRou** [comment]
Staking 100% still doesn't work for me and unstaking failes also.
Unstake (1 of 3 tries): https://explorer.testnet.rsk.co/tx/0xf0e3a90dbbea2889471c6798298585854e7f52c4f7ec4cc2033e55987e394188
Stake (confirm button only unlocks when I remove some decimals);
image

**Review by ShynRou — CHANGES_REQUESTED** [review]
See comment above.

**Comment by pietro-maximoff** [comment]
> See comment above.

yes, i have a call with @JoeStorm99 about the same issue, and i added fix for this already

**Comment by pietro-maximoff** [comment]
> Staking 100% still doesn't work for me and unstaking failes also.
> Unstake (1 of 3 tries):

Stan deployed Staking and StakingRewards to testnet, so I believe the issue with unstaking is related to that.
"StakingProxyTN": "0x38B0f49Dfe345EAF9B691718F8fE725835a17Bfb",
"StakingRewardsProxyTN": "0x128844463910C8724144e6Bb99F1AfaF202882AC""
I tested with the new staking address and everything is fine, 
note that the duration has also been changed from 14 days to 1 day to make it easier to test on the test network.

**Review by ShynRou — DISMISSED** [review]
Looks good now.

**Review by tiltom — DISMISSED** [review]

**Comment by soulBit** [comment]
Pietro is fixing the same issue with Increase Stake, once that is resolved we can merge this PR

**Pull request merged**
