### PR TITLE
Feat: Storybook Design Guide

### PR DESCRIPTION
**Pull request by ShynRou**
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2399958058

Design Guide should be visible on /storybook

### CODE REVIEW

**Comment by ShynRou** [comment]
Ahrg... the combined tailwind strings don't work. As they get removed on the ci build… will need to fix that.

**Comment by ShynRou** [comment]
Fixed the tailwind css issues. I had to use the values as style objects since tailwind will just strip out all the dynamic classes.

**Review by creed-victor — APPROVED** [review]

**Comment by creed-victor** [comment]
Looks ok, but maybe it would be worth adding example on how to use these classes. For example guideline for border radius, tailwind classname is actually `tw-rounded-{value}`, but from example dev may expect that `tw-radius-{value}` would work

**Review by tiltom — DISMISSED** [review]
Looking good, I just adjusted doc links so they open in a new tab.

**Review by creed-victor — DISMISSED** [review]

**Review by tiltom — APPROVED** [review]

**Review by creed-victor — APPROVED** [review]

**Review by soulBit — APPROVED** [review]

**Pull request merged**
