### PR TITLE
feat: mainnet contracts for btc <-> btcs

### PR DESCRIPTION
**Pull request by creed-victor**
https://sovryn.monday.com/boards/2218344956/pulses/2603230207

AC:
- Deposit of BTCS works in perpetuals page using native BTC (Fund Account)
- Withdrawal of BTCS to native BTC works in perpetuals page

Note: this is for mainnet, so testing should be done at https://staging.sovryn.app/perpetuals

### CODE REVIEW

**Review by ShynRou — DISMISSED** [review]

**Review by tiltom — DISMISSED** [review]

**Comment by jjmr007** [comment]
I was trying to go to: https://staging.sovryn.app/perpetuals
but it drives me to a "not found" page --> `Not Found - Request ID: 01G64EC86H1TBABQ2W4APJ3GPV`
so I'm unable to prefrom the tests to send BTC to BTCs (mainnet)

**Comment by jjmr007** [comment]
According the acceptance criteria, it seems we are testing the bridge BTC <--> BTCs (Bitcoin-- Binance), but according the link for [list of changes](https://github.com/DistributedCollective/Sovryn-frontend/pull/2164/files), it seems we are just talking about the bridge RSK <--> BSC for sending rBTC <--> BTCs which I already tested succesfully [here](https://sovryn.monday.com/boards/2175753614/pulses/2819188680).

Is this what we are trying to test here?, coz in such case this PR should be approved. Please let me know @creed-victor

**Comment by creed-victor** [comment]
> I was trying to go to: https://staging.sovryn.app/perpetuals but it drives me to a "not found" page --> `Not Found - Request ID: 01G64EC86H1TBABQ2W4APJ3GPV` so I'm unable to prefrom the tests to send BTC to BTCs (mainnet)

Use this as your staging link:
https://feat-btcs-mainnet--legacy-dapp.netlify.app/

**Comment by creed-victor** [comment]
> According the acceptance criteria, it seems we are testing the bridge BTC <--> BTCs (Bitcoin-- Binance), but according the link for [list of changes](https://github.com/DistributedCollective/Sovryn-frontend/pull/2164/files), it seems we are just talking about the bridge RSK <--> BSC for sending rBTC <--> BTCs which I already tested succesfully [here](https://sovryn.monday.com/boards/2175753614/pulses/2819188680).
> 
> Is this what we are trying to test here?, coz in such case this PR should be approved. Please let me know @creed-victor

This PR is for BTC (native btc) <-> BTCS deposits and withdrawals (using Fast BTC), RBTC <-> BTCS was already tested and approved in another task

**Review by jjmr007 — APPROVED** [review]
Bridge on mainnet networks to send and receive BTC <--> BTCs tested succesfully

**Review by soulBit — APPROVED** [review]
BTC -> BTCS transfer worked well (and vice-versa)

**Pull request merged**
