### PR TITLE
[Lend] - added date format to users locale #1502

### PR DESCRIPTION
**Pull request by pietro-maximoff**

### CODE REVIEW

**Review by tiltom — APPROVED** [review]

**Comment by ShynRou** [comment]
@pietro-maximoff moment will be replaced with dayjs soon #1569. Depending on the merge order this PR or the other has to be updated.

**Comment by pietro-maximoff** [comment]
> @pietro-maximoff moment will be replaced with dayjs soon #1569. Depending on the merge order this PR or the other has to be updated.

ah, got it, then i will change it after we discuss with Tzu about dates format in general

**Comment by soulBit** [comment]
@pietro-maximoff #1569 has been merged now

**Review by grinry — CHANGES_REQUESTED** [review]
Replace `moment` with `dayjs` as per #1569

**Pull request closed without merging**
