### PR TITLE
Update loot drop promos date

### PR DESCRIPTION
**Pull request by tiltom**
https://taiga.sovryn.app/project/sovryn-light/task/67

### CODE REVIEW

**Review by soulBit — APPROVED** [review]

**Review by rick23p — APPROVED** [review]

**Comment by rick23p** [comment]
What do you think guys if we could make a LootDrop JSON and put all loot drops in there and read from it in different places?
@tiltom @soulBit

**Comment by tiltom** [comment]
> What do you think guys if we could make a LootDrop JSON and put all loot drops in there and read from it in different places?
> @tiltom @soulBit

This could be good if we wanted non-technical people to be able to adjust the loot drops but I doubt they will want to do it. We would also need to adjust the code for it.

What do you think @soulBit ?

**Comment by soulBit** [comment]
@rick23p @tiltom let's discuss this in standup today, I agree that we should find a less manual way of updating these

**Comment by tiltom** [comment]
> @rick23p @tiltom let's discuss this in standup today, I agree that we should find a less manual way of updating these

Ok we can discuss it but it could work as Rick proposed - we would have a JSON file that could be edited by anyone and we would read loot drop info from it. But it needs validation with marketing people that they will use it because we would need to implement it.

**Pull request merged**
