### PR TITLE
bug/1436-buttons-yield-farm

### PR DESCRIPTION
**Pull request by boltsr**
fix buttons on yield farming page

### CODE REVIEW

**Comment by pietro-maximoff** [comment]
this bug still on 1365px resolution https://prnt.sc/196reau and lower

**Comment by boltsr** [comment]
@pietro-maximoff  Please check again

**Comment by pietro-maximoff** [comment]
> @pietro-maximoff Please check again

still have an issue https://prnt.sc/199t0r1, but on the release branch seems all good

**Comment by soulBit** [comment]
Closing this as discussed, issue will be resolved when release branch is merged back into development

**Pull request closed without merging**
