### PR TITLE
Show connected user wallet address in babelfish flows

### PR DESCRIPTION
**Pull request by creed-victor**
- shows receiver wallet (wallet originally connected to rsk chain) in deposit flow
- shows currently connected (rsk) wallet in withdrawal flow
- changes "available balance" with "max withdrawal" in withdraw flow

### CODE REVIEW

**Comment by bitcoinuser** [comment]
Hi @creed-victor. I'm testing it and I see a bug:

On Metamask usually when needed to change network, the Metamask window popup. In this case it doesn't, even clicking on BSC Network button on center.

Captura de tela de 2021-08-11 10-48-43

**Comment by creed-victor** [comment]
> Hi @creed-victor. I'm testing it and I see a bug:
> 
> On Metamask usually when needed to change network, the Metamask window popup. In this case it doesn't, even clicking on BSC Network button on center.
> 

I think @rick23p is implementing this metamask feature as another task.

**Comment by tiltom** [comment]
I don't like that sometimes we have information on two rows and it's unnecessary because we have a ton of space. I know it's probably not so relevant to the PR but I think we can adjust it here since it would be really quick fix.

image

**Comment by rick23p** [comment]
> @t-z-u , @creed-victor - I don't like that sometimes we have information on two rows and it's unnecessary because we have a ton of space. I know it's probably not so relevant to the PR but I think we can adjust it here since it would be really quick fix.
> 
> image

increased the width on https://github.com/DistributedCollective/Sovryn-frontend/pull/1606

**Review by tiltom — APPROVED** [review]

**Comment by bitcoinuser** [comment]
UI improvement: On my screen buttons are very near. See:

Captura de tela de 2021-08-16 10-30-26

**Comment by bitcoinuser** [comment]
Captura de tela de 2021-08-16 10-35-27

**Pull request merged**
